In [2]:
import pandas as pd
df = pd.read_csv("../data/Library_Usage.csv")

In [4]:
#Filtern aller Einträge (Zeilen), die über 10000 Ausleihen haben
df.loc[df['Total Checkouts']>10000]

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
851,9,SPECIAL,18064,2268,60 to 64 years,X,Main Library,July,2016,p,phone,False,2003,False,NaN
1963,0,ADULT,10521,621,60 to 64 years,X,Main Library,July,2016,p,phone,False,2003,False,6.0
3499,0,ADULT,12740,2209,45 to 54 years,C2,Chinatown,July,2016,z,email,True,2003,False,3.0
20042,3,SENIOR,16060,66,65 to 74 years,C2,Chinatown,July,2016,a,print,False,2003,False,3.0
31315,0,ADULT,13784,74,60 to 64 years,M4,Merced,June,2016,z,email,True,2003,False,11.0
39585,0,ADULT,11086,1083,35 to 44 years,C2,Chinatown,July,2016,p,phone,False,2003,False,3.0
57239,0,ADULT,10906,1421,45 to 54 years,P1,Park,July,2016,z,email,True,2003,False,8.0
86662,3,SENIOR,11748,963,65 to 74 years,X,Main Library,July,2016,z,email,True,2003,False,5.0
117628,0,ADULT,11817,2859,45 to 54 years,S7,Sunset,July,2016,z,email,True,2003,False,4.0
120604,3,SENIOR,10108,59,65 to 74 years,X,Main Library,November,2013,p,phone,False,2003,False,6.0
129341,3,SENIOR,12757,500,65 to 74 years,R3,Richmond,July,2016,p,phone,False,2004,False,NaN
138351,0,ADULT,10809,24,20 to 24 years,S7,Sunset,July,2016,z,email,True,2010,False,4.0
145600,3,SENIOR,11871,50,65 to 74 years,M4,Merced,July,2016,z,email,True,2003,False,7.0
146615,0,ADULT,24093,383,45 to 54 years,X,Main Library,July,2016,p,phone,True,2003,False,4.0
156806,0,ADULT,17308,257,60 to 64 years,X,Main Library,July,2016,z,email,True,2003,False,6.0
163893,3,SENIOR,25223,448,65 to 74 years,X,Main Library,July,2016,p,phone,False,2006,False,9.0
176606,0,ADULT,10371,1345,55 to 59 years,S7,Sunset,July,2016,z,email,True,2003,False,4.0
200204,3,SENIOR,18397,6,65 to 74 years,X,Main Library,July,2016,z,email,True,2005,False,NaN
216300,0,ADULT,12950,1548,60 to 64 years,O7,Ortega,July,2016,z,email,True,2003,False,4.0
222889,3,SENIOR,14502,3517,65 to 74 years,E7,Eureka Valley/Harvey Milk Memorial,July,2016,z,email,True,2006,False,8.0
227568,3,SENIOR,11147,123,65 to 74 years,M6,Mission,July,2016,a,print,False,2003,False,NaN
231807,3,SENIOR,11896,1408,65 to 74 years,E7,Eureka Valley/Harvey Milk Memorial,July,2016,z,email,True,2003,False,8.0
237668,0,ADULT,15505,294,60 to 64 years,X,Main Library,July,2016,p,phone,False,2004,False,6.0
255021,3,SENIOR,11102,2652,65 to 74 years,X,Main Library,July,2016,z,email,True,2003,False,NaN
278408,3,SENIOR,11366,62,65 to 74 years,X,Main Library,July,2016,z,email,True,2003,False,8.0
288655,0,ADULT,15598,228,55 to 59 years,X,Main Library,July,2016,p,phone,False,2003,False,11.0
290980,0,ADULT,12733,60,45 to 54 years,X,Main Library,July,2016,z,email,True,2003,False,8.0
293371,0,ADULT,35907,116,35 to 44 years,V3,Visitacion Valley,July,2016,p,phone,False,2003,False,NaN
294129,0,ADULT,10863,57,45 to 54 years,M6,Mission,July,2016,p,phone,False,2003,False,6.0
330536,3,SENIOR,10637,148,75 years and over,C2,Chinatown,January,2015,p,phone,False,2003,False,3.0
401287,5,STAFF,13362,1926,0 to 9 years,X,Main Library,July,2016,z,email,True,2004,True,NaN

In [5]:
#Alternative Lösung mit einer Hilfsvariable
row_filter = df['Total Checkouts']>10000
df.loc[row_filter]

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
851,9,SPECIAL,18064,2268,60 to 64 years,X,Main Library,July,2016,p,phone,False,2003,False,NaN
1963,0,ADULT,10521,621,60 to 64 years,X,Main Library,July,2016,p,phone,False,2003,False,6.0
3499,0,ADULT,12740,2209,45 to 54 years,C2,Chinatown,July,2016,z,email,True,2003,False,3.0
20042,3,SENIOR,16060,66,65 to 74 years,C2,Chinatown,July,2016,a,print,False,2003,False,3.0
31315,0,ADULT,13784,74,60 to 64 years,M4,Merced,June,2016,z,email,True,2003,False,11.0
39585,0,ADULT,11086,1083,35 to 44 years,C2,Chinatown,July,2016,p,phone,False,2003,False,3.0
57239,0,ADULT,10906,1421,45 to 54 years,P1,Park,July,2016,z,email,True,2003,False,8.0
86662,3,SENIOR,11748,963,65 to 74 years,X,Main Library,July,2016,z,email,True,2003,False,5.0
117628,0,ADULT,11817,2859,45 to 54 years,S7,Sunset,July,2016,z,email,True,2003,False,4.0
120604,3,SENIOR,10108,59,65 to 74 years,X,Main Library,November,2013,p,phone,False,2003,False,6.0
129341,3,SENIOR,12757,500,65 to 74 years,R3,Richmond,July,2016,p,phone,False,2004,False,NaN
138351,0,ADULT,10809,24,20 to 24 years,S7,Sunset,July,2016,z,email,True,2010,False,4.0
145600,3,SENIOR,11871,50,65 to 74 years,M4,Merced,July,2016,z,email,True,2003,False,7.0
146615,0,ADULT,24093,383,45 to 54 years,X,Main Library,July,2016,p,phone,True,2003,False,4.0
156806,0,ADULT,17308,257,60 to 64 years,X,Main Library,July,2016,z,email,True,2003,False,6.0
163893,3,SENIOR,25223,448,65 to 74 years,X,Main Library,July,2016,p,phone,False,2006,False,9.0
176606,0,ADULT,10371,1345,55 to 59 years,S7,Sunset,July,2016,z,email,True,2003,False,4.0
200204,3,SENIOR,18397,6,65 to 74 years,X,Main Library,July,2016,z,email,True,2005,False,NaN
216300,0,ADULT,12950,1548,60 to 64 years,O7,Ortega,July,2016,z,email,True,2003,False,4.0
222889,3,SENIOR,14502,3517,65 to 74 years,E7,Eureka Valley/Harvey Milk Memorial,July,2016,z,email,True,2006,False,8.0
227568,3,SENIOR,11147,123,65 to 74 years,M6,Mission,July,2016,a,print,False,2003,False,NaN
231807,3,SENIOR,11896,1408,65 to 74 years,E7,Eureka Valley/Harvey Milk Memorial,July,2016,z,email,True,2003,False,8.0
237668,0,ADULT,15505,294,60 to 64 years,X,Main Library,July,2016,p,phone,False,2004,False,6.0
255021,3,SENIOR,11102,2652,65 to 74 years,X,Main Library,July,2016,z,email,True,2003,False,NaN
278408,3,SENIOR,11366,62,65 to 74 years,X,Main Library,July,2016,z,email,True,2003,False,8.0
288655,0,ADULT,15598,228,55 to 59 years,X,Main Library,July,2016,p,phone,False,2003,False,11.0
290980,0,ADULT,12733,60,45 to 54 years,X,Main Library,July,2016,z,email,True,2003,False,8.0
293371,0,ADULT,35907,116,35 to 44 years,V3,Visitacion Valley,July,2016,p,phone,False,2003,False,NaN
294129,0,ADULT,10863,57,45 to 54 years,M6,Mission,July,2016,p,phone,False,2003,False,6.0
330536,3,SENIOR,10637,148,75 years and over,C2,Chinatown,January,2015,p,phone,False,2003,False,3.0
401287,5,STAFF,13362,1926,0 to 9 years,X,Main Library,July,2016,z,email,True,2004,True,NaN